### ISSUE TITLE
AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [xwartz/douban.fm#12]
Would you be interested to provide an [AppImage](http://appimage.org/) for Linux? electron-builder now has support for it that [makes it really easy](https://github.com/electron-userland/electron-builder/issues/504#issuecomment-233170607) to do.

**Comment by xwartz** [comment]
Yeah, https://github.com/xwartz/PupaFM/releases/tag/v1.2.1

**Comment by probonopd** [comment]
Cool, thanks!
