### ISSUE TITLE
无法克隆?

### ISSUE THREAD

**Issue by amhoho** [xwartz/douban.fm#15]
C:\Users\Administrator>git clone git@github.com:xwartz/PupaFM.git
Cloning into 'PupaFM'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of know
n hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

C:\Users\Administrator>git clone git@github.com:xwartz/PupaFM.git
Cloning into 'PupaFM'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by xwartz** [comment]
应该是你 git SSH 配置有问题

**Comment by amhoho** [comment]
那git其它的东西都是正常的啊,咋个唯独你家的就不行了,好奇怪的.有点郁闷

**Comment by xwartz** [comment]
不知道哦，没做什么限制
