### ISSUE TITLE
NPM error on Win 10

### ISSUE THREAD

**Issue by lorenmt** [xwartz/douban.fm#3]
Hi, I received the following errors when installing using npm. I have tried both npm v4.4.5 and v6.4.2, both of them failed.

The error message is the following:

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\Program\nodejs\node.exe" "D:\Program\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build-renderer"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! PupaFM@1.1.1 build-renderer: `cross-env NODE_ENV=production node -r babel-register ./node_modules/.bin/webpack --config webpack.config.pro.js --progress --profile --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PupaFM@1.1.1 build-renderer script 'cross-env NODE_ENV=production node -r babel-register ./node_modules/.bin/webpack --config webpack.config.pro.js --progress --profile --colors'.
npm ERR! This is most likely a problem with the PupaFM package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node -r babel-register ./node_modules/.bin/webpack --config webpack.config.pro.js --progress --profile --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PupaFM
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls PupaFM
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Program\PupaFM\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\Program\nodejs\node.exe" "D:\Program\nodejs\node_modules\npm\bin\npm-cli.js" "run" "compile"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! PupaFM@1.1.1 compile: `npm run build-renderer && npm run build-main`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PupaFM@1.1.1 compile script 'npm run build-renderer && npm run build-main'.
npm ERR! This is most likely a problem with the PupaFM package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-renderer && npm run build-main
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PupaFM
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls PupaFM
npm ERR! There is likely additional logging output above.

Thanks for the help.

**Comment by xwartz** [comment]
Sorry, @LorenMt 
I have no windows device. You may need google for help.

It might helps:  
https://www.google.com/search?q=npm+ERR!+code+ELIFECYCLE&oq=npm+ERR!+code+ELIFECYCLE&aqs=chrome..69i57j69i64l2.249j0j1&sourceid=chrome&ie=UTF-8

https://www.google.com/search?q=npm+ERR!+argv+%22D%3A%5CProgram%5Cnodejs%5Cnode.exe%22&oq=npm+ERR!+argv+%22D%3A%5CProgram%5Cnodejs%5Cnode.exe%22&aqs=chrome..69i57j69i64l2.264j0j1&sourceid=chrome&ie=UTF-8
